spring.datasource.url=jdbc:postgresql://localhost:5432/easyazul
spring.datasource.username=postgres
spring.datasource.password=postgres
server.port=8081

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG
logging.level.org.springframework.boot.autoconfigure=DEBUG

api.security.token.secret=${JWT_SECRET:12345678}

server.error.include-stacktrace=never
app.timezone=America/Sao_Paulo